package folders

import (
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"errors"
	"fmt"
	"log/slog"
	"net/http"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"golang.org/x/crypto/bcrypt"

	"foldex/internal/pkg/httperr"
)

// HashPassword bcrypt-hashes a plaintext folder password for storage in
// folder.password_hash. Never store or log the plaintext.
func HashPassword(plain string) (string, error) {
	b, err := bcrypt.GenerateFromPassword([]byte(plain), bcrypt.DefaultCost)
	if err != nil {
		return "", fmt.Errorf("hash password: %w", err)
	}
	return string(b), nil
}

// VerifyPassword reports whether plain matches the bcrypt hash.
func VerifyPassword(hash, plain string) bool {
	return bcrypt.CompareHashAndPassword([]byte(hash), []byte(plain)) == nil
}

// unlockTokenTTL is a safety ceiling, not the intended session length — the
// frontend never persists the token past a page reload (CLAUDE.md-documented
// decision: unlock state is session-only), so this just bounds how long a
// token could theoretically be replayed if it leaked.
const unlockTokenTTL = 24 * time.Hour

// UnlockHeader carries a folder unlock token on requests that read a
// protected folder's contents — checked by both this package's own
// parent_id-scoped List and internal/entries' folder_id-scoped List.
const UnlockHeader = "X-Foldex-Folder-Unlock"

// IssueUnlockToken mints a token proving the caller supplied the correct
// password for folderID at issuance time. The HMAC input includes the
// folder's CURRENT password_hash, so changing or clearing the password
// invalidates every previously issued token automatically — no separate
// revocation list needed.
func IssueUnlockToken(secret []byte, folderID int64, passwordHash string) string {
	exp := time.Now().Add(unlockTokenTTL).Unix()
	return signUnlockToken(secret, folderID, passwordHash, exp) + "." + strconv.FormatInt(exp, 10)
}

// VerifyUnlockToken checks a token against the folder's CURRENT password
// hash (fetched fresh from the DB by the caller, never trusted from the
// token itself) and expiry.
func VerifyUnlockToken(secret []byte, folderID int64, passwordHash, token string) bool {
	mac, expStr, ok := strings.Cut(token, ".")
	if !ok {
		return false
	}
	exp, err := strconv.ParseInt(expStr, 10, 64)
	if err != nil || time.Now().Unix() > exp {
		return false
	}
	expected := signUnlockToken(secret, folderID, passwordHash, exp)
	return hmac.Equal([]byte(mac), []byte(expected))
}

func signUnlockToken(secret []byte, folderID int64, passwordHash string, exp int64) string {
	mac := hmac.New(sha256.New, secret)
	mac.Write([]byte(fmt.Sprintf("%d:%d:%s", folderID, exp, passwordHash)))
	return hex.EncodeToString(mac.Sum(nil))
}

// CheckUnlock enforces the content-gate for a single folder: nil (allowed)
// when the folder is unprotected (passwordHash == nil), or when token
// verifies against the folder's current password hash; otherwise a typed
// 403 folder_locked error. Redaction of preview_links/preview_folders (the
// OTHER half of the protection story) happens unconditionally in the
// repository layer regardless of token presence — this function only gates
// the two "reveal real contents" endpoints (entries.List folder_id, this
// package's own List parent_id).
func CheckUnlock(secret []byte, folderID int64, passwordHash *string, token string) error {
	if passwordHash == nil {
		return nil
	}
	if token == "" || !VerifyUnlockToken(secret, folderID, *passwordHash, token) {
		return httperr.New(http.StatusForbidden, "folder_locked", "this folder is password-protected")
	}
	return nil
}

// LoadOrGenerateFolderUnlockKey mirrors push.LoadOrGenerate's env→file→
// autogen(0600)→persist pattern for the folder-unlock-token HMAC secret.
// envKeyB64 (FOLDER_UNLOCK_KEY) is a base64-encoded explicit override;
// statePath (FOLDER_UNLOCK_KEY_PATH) persists an autogenerated key across
// restarts, same volume VAPID's state file uses.
func LoadOrGenerateFolderUnlockKey(envKeyB64, statePath string, autoGen bool, logger *slog.Logger) ([]byte, error) {
	if envKeyB64 != "" {
		key, err := base64.StdEncoding.DecodeString(envKeyB64)
		if err != nil {
			return nil, fmt.Errorf("FOLDER_UNLOCK_KEY is not valid base64: %w", err)
		}
		if len(key) < 32 {
			return nil, errors.New("FOLDER_UNLOCK_KEY must decode to at least 32 bytes")
		}
		return key, nil
	}

	if statePath != "" {
		if key, err := readUnlockKeyState(statePath); err == nil {
			return key, nil
		}
	}

	if !autoGen {
		return nil, errors.New(
			"folder unlock key not configured: set FOLDER_UNLOCK_KEY (base64, 32+ bytes), " +
				"or set FOLDER_UNLOCK_AUTO_GENERATE=1 to let the server generate and persist one on first boot",
		)
	}

	key := make([]byte, 32)
	if _, err := rand.Read(key); err != nil {
		return nil, fmt.Errorf("generate folder unlock key: %w", err)
	}
	if statePath == "" {
		logger.Warn("folder unlock key: generated session-only key (FOLDER_UNLOCK_KEY_PATH empty) — every existing unlock token becomes invalid on restart")
		return key, nil
	}
	if err := writeUnlockKeyState(statePath, key); err != nil {
		// Persist failure is a warn, not fatal — the in-memory key still
		// works for this boot. Next boot regenerates (invalidates existing
		// unlock tokens, which is harmless: users just re-enter the
		// password, matching the session-only unlock model anyway).
		logger.Warn("folder unlock key: persist failed, key is session-only", "path", statePath, "err", err)
	} else {
		logger.Info("folder unlock key: generated and persisted", "path", statePath)
	}
	return key, nil
}

func readUnlockKeyState(path string) ([]byte, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	key, err := base64.StdEncoding.DecodeString(strings.TrimSpace(string(data)))
	if err != nil {
		return nil, err
	}
	if len(key) < 32 {
		return nil, errors.New("state file key too short")
	}
	return key, nil
}

func writeUnlockKeyState(path string, key []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	encoded := base64.StdEncoding.EncodeToString(key)
	// 0600: this key lets anyone mint a valid unlock token for any protected
	// folder without ever knowing its password — treat it like the VAPID
	// private key.
	return os.WriteFile(path, []byte(encoded), 0o600)
}
