// Auto-generated by scripts/bump-version.mjs (runs as `prebuild`). Do NOT edit
// by hand — your changes will be clobbered on the next build.
export const VERSION = '1.0.7'
export const BUILD_DATE = '2026-05-14'
