// Package keyfile resolves a long-lived symmetric key from the operator's
// configuration, following the env → file → autogenerate(0600) shape that
// push.LoadOrGenerate established for the VAPID private key.
//
// It exists so the two keys that already needed this — the folder-unlock HMAC
// secret (ADR-28) and the TOTP seed-encryption key (PR3) — share one
// implementation, and so the NEXT one does not become a third copy.
//
// The parameter that matters is AllowEphemeral, because the two keys fail in
// opposite ways. Losing the folder-unlock key invalidates outstanding unlock
// tokens and users simply re-enter their folder password; losing the TOTP
// encryption key makes every stored seed permanently undecryptable and locks
// every 2FA user out of their own account. A key of the second kind must never
// be quietly regenerated.
package keyfile

import (
	"crypto/rand"
	"encoding/base64"
	"errors"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"strings"
)

// MinKeyBytes is the floor for every key this package hands out. 32 bytes is
// both a full-strength HMAC-SHA256 key and an AES-256 key.
const MinKeyBytes = 32

// Config describes one key's resolution policy.
type Config struct {
	// Name is the operator-facing label used in errors and logs, e.g.
	// "folder unlock key". It is never the key material.
	Name string
	// EnvVar / PathVar are the environment variable NAMES, quoted in error
	// messages so the operator is told exactly which knob to set.
	EnvVar  string
	PathVar string

	// EnvValue is the base64 key supplied through EnvVar, if any.
	EnvValue string
	// Path persists an autogenerated key across restarts.
	Path string
	// AutoGenerate permits minting a key when neither EnvValue nor Path yields
	// one.
	AutoGenerate bool
	// AllowEphemeral permits continuing with an in-memory key when it cannot be
	// persisted. Set it only when losing the key is recoverable by the user
	// unaided. When false, a persist failure is a boot failure — which is the
	// correct outcome for a key that encrypts data at rest, because starting
	// successfully and only discovering the loss at the next restart destroys
	// the data in between.
	AllowEphemeral bool
}

// Load resolves the key: explicit env value, else the persisted state file,
// else (when permitted) a fresh key written to Path.
func Load(cfg Config, logger *slog.Logger) ([]byte, error) {
	if cfg.EnvValue != "" {
		key, err := base64.StdEncoding.DecodeString(strings.TrimSpace(cfg.EnvValue))
		if err != nil {
			return nil, fmt.Errorf("%s is not valid base64: %w", cfg.EnvVar, err)
		}
		if len(key) < MinKeyBytes {
			return nil, fmt.Errorf("%s must decode to at least %d bytes", cfg.EnvVar, MinKeyBytes)
		}
		return key, nil
	}

	if cfg.Path != "" {
		if key, err := Read(cfg.Path); err == nil {
			return key, nil
		}
	}

	if !cfg.AutoGenerate {
		return nil, fmt.Errorf(
			"%s not configured: set %s (base64, %d+ bytes), or enable auto-generation",
			cfg.Name, cfg.EnvVar, MinKeyBytes)
	}

	key := make([]byte, MinKeyBytes)
	if _, err := rand.Read(key); err != nil {
		return nil, fmt.Errorf("generate %s: %w", cfg.Name, err)
	}

	if cfg.Path == "" {
		if !cfg.AllowEphemeral {
			return nil, fmt.Errorf(
				"%s cannot be session-only: set %s so the generated key survives a restart",
				cfg.Name, cfg.PathVar)
		}
		logger.Warn(cfg.Name+": generated a session-only key", "hint", cfg.PathVar+" is empty")
		return key, nil
	}
	if err := Write(cfg.Path, key); err != nil {
		if !cfg.AllowEphemeral {
			return nil, fmt.Errorf("persist %s to %s: %w", cfg.Name, cfg.Path, err)
		}
		logger.Warn(cfg.Name+": persist failed, key is session-only", "path", cfg.Path, "err", err)
		return key, nil
	}
	logger.Info(cfg.Name+": generated and persisted", "path", cfg.Path)
	return key, nil
}

// Read loads a base64 key from a state file.
func Read(path string) ([]byte, error) {
	// path is operator configuration, never request input. Clean and reject the
	// empty case before ReadFile so gosec G304 is satisfied without pretending
	// the path is untrusted.
	path = filepath.Clean(path)
	if path == "." || path == "" {
		return nil, errors.New("empty key path")
	}
	data, err := os.ReadFile(path) //nolint:gosec // G304: operator-configured path only
	if err != nil {
		return nil, err
	}
	key, err := base64.StdEncoding.DecodeString(strings.TrimSpace(string(data)))
	if err != nil {
		return nil, err
	}
	if len(key) < MinKeyBytes {
		return nil, fmt.Errorf("state file key shorter than %d bytes", MinKeyBytes)
	}
	return key, nil
}

// Write persists a key at 0600.
func Write(path string, key []byte) error {
	path = filepath.Clean(path)
	if path == "." || path == "" {
		return errors.New("empty key path")
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		return err
	}
	// 0600 explicitly rather than trusting the process umask: these keys are as
	// sensitive as the VAPID private key — one mints folder-unlock tokens
	// without knowing any password, the other decrypts every TOTP seed.
	return os.WriteFile(path, []byte(base64.StdEncoding.EncodeToString(key)), 0o600)
}
